# Generated by Django 4.1.5 on 2023-01-18 03:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('image', models.CharField(max_length=300)),
                ('date_created', models.DateField()),
                ('description', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Cast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=300)),
                ('image', models.CharField(max_length=300)),
                ('actions', models.CharField(max_length=20)),
                ('weapon', models.CharField(max_length=20)),
                ('armour', models.CharField(max_length=20)),
                ('adventuring_skills', models.CharField(max_length=20)),
                ('stamina', models.CharField(max_length=20)),
                ('notes', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='CastType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Npc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=300)),
                ('image', models.CharField(max_length=300)),
                ('actions', models.CharField(max_length=20)),
                ('weapon', models.CharField(max_length=300)),
                ('armour', models.CharField(max_length=20)),
                ('adventuring_skills', models.CharField(max_length=20)),
                ('stamina', models.CharField(max_length=20)),
                ('notes', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='NpcType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.CharField(max_length=25)),
                ('first_name', models.CharField(max_length=25)),
                ('last_name', models.CharField(max_length=25)),
                ('bio', models.CharField(max_length=100)),
                ('profile_image_url', models.CharField(max_length=500)),
                ('email', models.EmailField(max_length=25)),
                ('created_on', models.DateField()),
                ('active', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='NpcCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('npc_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='warlockapi.npc')),
                ('npc_type_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='warlockapi.npctype')),
            ],
        ),
        migrations.CreateModel(
            name='NpcCampaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('campaign_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='warlockapi.campaign')),
                ('npc_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='warlockapi.npc')),
            ],
        ),
        migrations.AddField(
            model_name='npc',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='warlockapi.user'),
        ),
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('image', models.CharField(max_length=300)),
                ('community', models.CharField(max_length=50)),
                ('background', models.CharField(max_length=50)),
                ('career', models.CharField(max_length=50)),
                ('stamina', models.CharField(max_length=50)),
                ('luck', models.CharField(max_length=50)),
                ('pluck', models.CharField(max_length=50)),
                ('appraise_skill', models.CharField(max_length=50)),
                ('athletics_skill', models.CharField(max_length=50)),
                ('bargain_skill', models.CharField(max_length=50)),
                ('blunt_skill', models.CharField(max_length=50)),
                ('bow_skill', models.CharField(max_length=50)),
                ('brawling_skill', models.CharField(max_length=50)),
                ('command_skill', models.CharField(max_length=50)),
                ('crossbow_skill', models.CharField(max_length=50)),
                ('diplomacy_skill', models.CharField(max_length=50)),
                ('disguise_skill', models.CharField(max_length=50)),
                ('dodge_skill', models.CharField(max_length=50)),
                ('endurance_skill', models.CharField(max_length=50)),
                ('history_skill', models.CharField(max_length=50)),
                ('incabtaion_skill', models.CharField(max_length=50)),
                ('intimidate_skill', models.CharField(max_length=50)),
                ('language_skill', models.CharField(max_length=50)),
                ('large_blade_skill', models.CharField(max_length=50)),
                ('lie_skill', models.CharField(max_length=50)),
                ('medicine_skill', models.CharField(max_length=50)),
                ('navigation_skill', models.CharField(max_length=50)),
                ('ostler_skill', models.CharField(max_length=50)),
                ('persuasion_skill', models.CharField(max_length=50)),
                ('pole_arm_skill', models.CharField(max_length=50)),
                ('repair_skill', models.CharField(max_length=50)),
                ('sleight_of_hand_skill', models.CharField(max_length=50)),
                ('small_blade_skill', models.CharField(max_length=50)),
                ('spot_skill', models.CharField(max_length=50)),
                ('stealth_skill', models.CharField(max_length=50)),
                ('survival_skill', models.CharField(max_length=50)),
                ('swimming_skill', models.CharField(max_length=50)),
                ('thrown_skill', models.CharField(max_length=50)),
                ('possesions', models.CharField(max_length=50)),
                ('weapons', models.CharField(max_length=50)),
                ('traits', models.CharField(max_length=200)),
                ('notes', models.CharField(max_length=300)),
                ('spells', models.CharField(max_length=300)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='warlockapi.user')),
            ],
        ),
        migrations.CreateModel(
            name='CastCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cast_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='warlockapi.cast')),
                ('cast_type_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='warlockapi.casttype')),
            ],
        ),
        migrations.CreateModel(
            name='CastCampaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('campaign_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='warlockapi.campaign')),
                ('cast_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='warlockapi.cast')),
            ],
        ),
        migrations.AddField(
            model_name='cast',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='warlockapi.user'),
        ),
        migrations.AddField(
            model_name='campaign',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='warlockapi.user'),
        ),
    ]
