# Generated by Django 4.1.5 on 2023-02-02 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warlockapi', '0002_remove_campaign_date_created_campaign_data'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='campaign',
            name='data',
        ),
        migrations.AddField(
            model_name='campaign',
            name='data_created',
            field=models.DateTimeField(blank=True, default='2023-02-02 02:23:25', null=True),
        ),
    ]
