# Generated by Django 4.1.5 on 2023-02-02 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warlockapi', '0003_remove_campaign_data_campaign_data_created'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='campaign',
            name='data_created',
        ),
        migrations.AddField(
            model_name='campaign',
            name='date_created',
            field=models.DateTimeField(blank=True, default='2023-02-02 02:26:56', null=True),
        ),
    ]
