# Generated by Django 4.1.5 on 2023-02-02 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warlockapi', '0004_remove_campaign_data_created_campaign_date_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaign',
            name='date_created',
            field=models.DateTimeField(blank=True, default='2023-02-02 02:58:21', null=True),
        ),
    ]
